apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-example
  name: gitops-example
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gitops-example
  template:
    metadata:
      labels:
        app: gitops-example
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
        - image: gitops-example
          name: gitops-example
          ports:
            - name: http
              containerPort: 8050
