name: Green deployment to GKE

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}    
  GKE_ZONE:  ${{ secrets.GKE_ZONE }}   
  DEPLOYMENT_NAME: gitops-example 
  IMAGE: static-site

jobs:
  green-setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy Green
    runs-on: ubuntu-latest
    needs: approveapp
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
    - run: |-
        gcloud --quiet auth configure-docker
    
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE-green:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./app

    - name: Publish
      run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE-green:$GITHUB_SHA"

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize


    - name: Deploy
      run: |-
        cd k8s
        ../kustomize edit set image gcr.io/$PROJECT_ID/$IMAGE-green:TAG=gcr.io/$PROJECT_ID/$IMAGE-green:$GITHUB_SHA
        ../kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/gitops-example-green
        kubectl get services -o wide

    - name: Reject App
      run: |-
        kubectl delete deploy deployment/gitops-example-blue